### ISSUE TITLE
백그라운드 GPS 서비스 개발을 위한 라이브러리 채택

### ISSUE THREAD

**Issue by m1nsuplee** [zizon-developers/now-where-client#7]
이 프로젝트의 핵심은 상대방이 약속장소까지 얼마나 왔는지를 추적하는 것이 핵심임

그런데 위치 추적을 위해서는 앱이 종료되어도 백그라운드에서 GPS가 작동되어야함

그래서 알아봄

`react-native-background-geolocation`이라는 라이브러리를 써야할 것 같음

근데 안드로이드는 유료라고함

근데 우리는 iOS만 쓰니까 ㄱㅊ할 듯?

이 라이브러리는 두 개의 API를 제공함

1. 내비게이션처럼 사용자의 위치를 계속 트래킹 하는 Location-tracking API
- 근데 이걸 쓰면 앱이 종료되도 하루종일 트래킹해서 배터리 소모 개쩔듯ㅋㅋ
2. 반경의 출입을 감지하고 그에 따른 동작을 할 수 있는 Geofencing API
- 우리는 약속장소를 정해놓기 때문에 약속장소에 대한 반경을 만들 수가 있음. 그래서 이 반경에 출입했는지 감지되기 시작하면 그 떄부터 위치 추적하고 푸시를 보내야할 것 같음

그래서 결론적으로 내가 이걸 직접 개발할 수 있는 슈퍼개발자가 아니기 떄문에 이거 써야한다고 생각하는데 더 좋은 라이브러리가 있다면 알려주고, 그게 아니라면 이걸 쓰는게 어떰??

@ohs8283 @uhanuu

**Comment by ohs8283** [comment]
딱 우리가 사용할 라이브러리인거 같은데 낼 인나서 한번더 찾아보고 바로 이슈 날리겠습니답!

**Comment by m1nsuplee** [comment]
> 딱 우리가 사용할 라이브러리인거 같은데 낼 인나서 한번더 찾아보고 바로 이슈 날리겠습니답!

뭐 괜찮은 거 있나예?
